### PR TITLE
Add CentOS 9 to supported operating systems

### PR DESCRIPTION
**Pull request by kajinamit**
#### Pull Request (PR) description
This change adds CentOS Stream 9 (aka CentOS 9) to supported operating
systems.

#### This Pull Request (PR) fixes the following issues
N/A

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks @kajinamit for this PR! Please address the issues with the acceptance testing so that this can be merged.

**Comment by kajinamit** [comment]
It seems the upstream repo doesn't provide packages for CentOS9 yet. I'll fix that.

**Review by bastelfreak — APPROVED** [review]

**Comment by kajinamit** [comment]
The failure in Puppet6 + Ubuntu jobs are irrelevant to this change. it seems something is wrong with fact reference but I don't know why the problem is specific to puppet 6.

**Comment by smortex** [comment]
> it seems something is wrong with fact reference but I don't know why the problem is specific to puppet 6.

https://github.com/voxpupuli/puppet-rsyslog/blob/dfec1469af837e3f2ee1443a2e62e87fa1e4b759/spec/acceptance/base_spec.rb#L52

`os.distro.codename` needs `lsb-release` with legacy facter.

Fixed in some vox repos this way: https://github.com/voxpupuli/puppet-jenkins/commit/860af1e2e85f104904ed0e393387a6e38f254292

**Comment by bastelfreak** [comment]
I tried to fix it in https://github.com/voxpupuli/puppet-rsyslog/pull/201 but I currently do not know why it is not working.

**Comment by kajinamit** [comment]
The quite strange thing is that lsb-release is installed when software-properties-common is installed, but os.distro.codename is not properly looked up.

Is it possible that we ignore these failures atm and merge this change ? This has been kept for a while and I don't really like to keep it further because of that clearly broken tests which I'm not sure when we can fix. I've tried a few options I could think of but none of these works, and now I've run out of my ideas honestly speaking.

**Comment by jcpunk** [comment]
FYI, lsb-release isn't present on CentOS 9 at this time : https://bugzilla.redhat.com/show_bug.cgi?id=2012924

**Comment by bastelfreak** [comment]
@kajinamit can you please rebase this one as well?

**Review by jhoblitt — APPROVED** [review]
LGTM

**Pull request merged**
