### PR TITLE
Add warning to indicate that the files are managed by Puppet.

### PR DESCRIPTION
**Pull request by bschonec**
#### Pull Request (PR) description

Add a "managed by puppet" warning to the beginning of all configuration files 

#### This Pull Request (PR) fixes the following issues 

None of the configuration files managed by this module identify themselves as "Managed by Puppet, do not edit".  This small update fixes that issue.

### CODE REVIEW

**Comment by smortex** [comment]
CI failures are unrelated. I opened #216 to fix it.  Rebasing on top of it when merged should help!

**Comment by bschonec** [comment]
I have merged in the latest fixes but the workflow still fails.

**Comment by smortex** [comment]
> I have merged in the latest fixes but the workflow still fails.

I gave it a look and opened #231 :wink:.

**Review by smortex — APPROVED** [review]
That seems reasonable.

**Pull request merged**
