### PR TITLE
Remove Client/Server model and just use config

### PR DESCRIPTION
**Pull request by dhollinger**
#### Pull Request (PR) description
Removed the `rsyslog::server` and `rsyslog::client` classes and moved all functionality into the `rsyslog::config` class.

README and tests have been updated to reflect this

### CODE REVIEW

**Comment by trefzer** [comment]
remark: the example directory still uses rsyslog::client

**Comment by dhollinger** [comment]
> remark: the example directory still uses rsyslog::client

Fixing that now

**Comment by kenyon** [comment]
REFERENCE.md needed to be updated also.

**Comment by kenyon** [comment]
> What happened here? This new table of contents partially duplicates the previous one, but adds nonexistent sections.

#158 should fix this.

**Pull request merged**
